# Generated by Django 4.1.3 on 2022-11-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_data',
            name='platform_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
