# Generated by Django 4.1.3 on 2022-11-13 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_platform_data_platform_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecommerce_sites',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('website_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='platform_data',
            name='platform_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.ecommerce_sites'),
        ),
    ]
