# Generated by Django 4.1.3 on 2022-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_ecommerce_sites_alter_platform_data_platform_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_data',
            name='platform_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
