# Generated by Django 4.1.3 on 2022-11-13 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_platform_data_platform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_data',
            name='platform_id',
        ),
        migrations.DeleteModel(
            name='Ecommerce_sites',
        ),
    ]
