# Generated by Django 4.1.3 on 2022-11-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_platform_data_platform_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_data',
            name='platform_id',
        ),
        migrations.RemoveField(
            model_name='platform_data',
            name='platform_image',
        ),
    ]
