# Generated by Django 4.1.3 on 2022-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_platform_data_price_alter_platform_data_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_data',
            name='platform_name',
            field=models.CharField(blank=True, default='Amazon', max_length=200, null=True),
        ),
    ]
