# Generated by Django 4.1.3 on 2022-12-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_platform_data_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_data',
            name='expected_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
