# Generated by Django 4.1.3 on 2022-12-19 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_platform_data_expected_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_data',
            name='expected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
