# Generated by Django 4.1.3 on 2022-12-20 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_platform_data_expected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform_data',
            name='shipping_date',
            field=models.CharField(blank=True, default='20/12/2022', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='platform_data',
            name='expected_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 11, 24, 56, 656199)),
        ),
    ]
