# Generated by Django 4.1.3 on 2022-12-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_platform_data_shipping_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform_data',
            name='shipping_date',
        ),
        migrations.AlterField(
            model_name='platform_data',
            name='expected_date',
            field=models.CharField(blank=True, default='20/12/2022', max_length=200, null=True),
        ),
    ]
