# Generated by Django 4.1.3 on 2022-12-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_platform_data_shipping_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform_data',
            name='expected_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
