products = [
  {
    '_id': '1',
    'name': 'Quantum One',
    'image': '/images/jbl_headset.jpg',
    'description':
      'Casque gaming USB professionel avec son immersif QuantumSphere JBL à détection de mouvement - Micro à réduction de bruit - Compatible avec PC, Playstation, Xbox - Noir',
    'brand': 'JBL',
    'category': 'Electronics',
    'price': 122.50,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Apple iPhone 14 Plus (128 GB)',
    'image': '/images/iphone14_pluse.jpg',
    'description':
      'The iPhone 14 is equipped with the same A15 Bionic chip that was used in the iPhone 13 Pro. This chip powers all iPhone functions and keeps games and applications running smoothly. All this fun will last a long time thanks to the increased thermal efficiency of the iPhone\'s internal design.',
    'brand': 'Apple',
    'category': 'Electronics',
    'price': 1254.43,
    'countInStock': 5,
    'rating': 4.0,
    'numReviews': 8,
  },
  {
    '_id': '3',
    'name': 'Samsung S22 Ultra 5G 128GB Phantom Black',
    'image': '/images/samsung_ultra_s22.jpg',
    'description':
      'The epic standard in innovation Galaxy S22 Ultra is setting an epic new standard for power, creativity and performance.',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 1050.04,
    'countInStock': 5,
    'rating': 3,
    'numReviews': 12,
  },
  {
    '_id': '4',
    'name': 'OnePlus 10 Pro',
    'image': '/images/onepluse_10pro.jpg',
    'description':
      '5G 8 GB RAM 128 GB, Unlocked, with Hasselblad Camera for 2nd Generation Mobile Phones - 2 Years Warranty - Volcanic Black',
    'brand': 'Onepluse',
    'category': 'Electronics',
    'price': 805.87,
    'countInStock': 11,
    'rating': 5,
    'numReviews': 15,
  },
  {
    '_id': '5',
    'name': 'Xiaomi 12 Pro',
    'image': '/images/xiaomi_12pro.jpg',
    'description':
      'Professional arrangement of three 50 MP cameras.Snapdragon 8 Gen 1.WQHD + 120Hz AMOLED display.Xiaomi HyperCharge 120W smart charging',
    'brand': 'Xiaomi',
    'category': 'Electronics',
    'price': 892.65,
    'countInStock': 7,
    'rating': 3.5,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Samsung Galaxy Z Fold 4 256GB Black 7.6 5G (12GB) Android',
    'image': '/images/samsung_zfold.jpg',
    'description':
      'Black colour. 3.18 GHz Qualcomm Snapdragon 8+ Gen1 Octa-Core processor.50-megapixel main camera with optical image stabilization .9.2 cm (7.6 inch) Dynamic AMOLED display with a resolution of 2176 x 1812 pixels. 256 GB internal memory, water protection, Android 12.0',
    'brand': 'Samsung',
    'category': 'Electronics',
    'price': 1706.82,
    'countInStock': 0,
    'rating': 4,
    'numReviews': 4,
  },
]

